import http from 'node:http';
import {readFile} from 'node:fs/promises';
import {WebSocketServer,WebSocket} from 'ws';
import {randomUUID} from 'node:crypto';
import {BOXES,SPAWNS,move,rayBox} from './public/world.js';
const port=Number(process.env.PORT)||3000,players=new Map();
const routes={'/':'public/index.html','/style.css':'public/style.css','/game.js':'public/game.js','/world.js':'public/world.js','/three.js':'node_modules/three/build/three.module.js','/three.core.js':'node_modules/three/build/three.core.js'};
const server=http.createServer(async(req,res)=>{try{const path=new URL(req.url,'http://localhost').pathname;if(path==='/health'){res.writeHead(200,{'Content-Type':'application/json'});return res.end(JSON.stringify({ok:true,players:players.size}));}if(!routes[path]){res.writeHead(404);return res.end('Not found');}const data=await readFile(new URL(routes[path],import.meta.url));res.writeHead(200,{'Content-Type':path.endsWith('.js')?'text/javascript':path.endsWith('.css')?'text/css':'text/html','Cache-Control':'no-cache'});res.end(data);}catch{res.writeHead(500);res.end('Server error');}});
const wss=new WebSocketServer({server,maxPayload:2048});
const send=(ws,data)=>{if(ws.readyState===WebSocket.OPEN&&ws.bufferedAmount<65536)ws.send(JSON.stringify(data));};
const broadcast=(room,data)=>{for(const p of players.values())if(p.room===room)send(p.ws,data);};
function spawn(p){const others=[...players.values()].filter(v=>v!==p&&v.room===p.room&&v.hp>0);const pos=[...SPAWNS].sort((a,b)=>Math.min(100,...others.map(v=>Math.hypot(v.x-b[0],v.z-b[1])))-Math.min(100,...others.map(v=>Math.hypot(v.x-a[0],v.z-a[1]))))[0];p.x=pos[0];p.z=pos[1];p.hp=100;p.protectedUntil=Date.now()+1500;p.respawnAt=0;p.input={};}
wss.on('connection',ws=>{let p;let count=0;const rate=setInterval(()=>count=0,1000);const joinTimeout=setTimeout(()=>{if(!p)ws.close(1008,'Join timeout');},10000);ws.on('message',raw=>{if(++count>100)return ws.close(1008,'Rate limit');let m;try{m=JSON.parse(raw);}catch{return;}if(!m||typeof m!=='object')return;
if(m.type==='join'&&!p){const room=String(m.room||'public').toLowerCase().replace(/[^a-z0-9-]/g,'').slice(0,24)||'public';if([...players.values()].filter(v=>v.room===room).length>=12){send(ws,{type:'error',message:'このルームは満員です。別のルームを選んでください。'});return;}p={id:randomUUID(),ws,room,name:String(m.name||'Player').replace(/[<>\x00-\x1f]/g,'').trim().slice(0,16)||'Player',yaw:0,pitch:0,kills:0,deaths:0,lastShot:0,input:{}};spawn(p);players.set(p.id,p);clearTimeout(joinTimeout);send(ws,{type:'welcome',id:p.id,room});broadcast(room,{type:'notice',text:`${p.name} が参加しました`});}
if(!p)return;if(m.type==='input'){p.input={};for(const key of ['forward','back','left','right','fire'])p.input[key]=m[key]===true;if(Number.isFinite(m.yaw))p.yaw=m.yaw%(Math.PI*2);if(Number.isFinite(m.pitch))p.pitch=Math.max(-1.35,Math.min(1.35,m.pitch));p.lastInput=Date.now();}});ws.on('error',()=>{});ws.on('close',()=>{clearInterval(rate);clearTimeout(joinTimeout);if(p){players.delete(p.id);broadcast(p.room,{type:'notice',text:`${p.name} が退出しました`});}});});
function shoot(p,now){p.lastShot=now;p.protectedUntil=0;const o=[p.x,1.65,p.z],d=[-Math.sin(p.yaw)*Math.cos(p.pitch),Math.sin(p.pitch),-Math.cos(p.yaw)*Math.cos(p.pitch)];let dist=80,target=null;for(const [x,z,w,h,l]of BOXES)dist=Math.min(dist,rayBox(o,d,[x-w/2,0,z-l/2],[x+w/2,h,z+l/2]));for(const q of players.values()){if(q===p||q.room!==p.room||q.hp<=0||q.protectedUntil>now)continue;const hit=rayBox(o,d,[q.x-.45,0,q.z-.45],[q.x+.45,2,q.z+.45]);if(hit<dist){dist=hit;target=q;}}if(target){target.hp=Math.max(0,target.hp-25);send(p.ws,{type:'hit',kill:target.hp===0});if(target.hp===0){p.kills++;target.deaths++;target.respawnAt=now+3000;target.input={};broadcast(p.room,{type:'notice',text:`${p.name} → ${target.name}`});}}broadcast(p.room,{type:'shot',id:p.id,from:o,to:o.map((v,i)=>v+d[i]*dist)});}
let last=Date.now();setInterval(()=>{const now=Date.now(),dt=Math.min((now-last)/1000,.05);last=now;const rooms=new Map();for(const p of players.values()){if(p.hp<=0){if(now>=p.respawnAt)spawn(p);}else{if(now-(p.lastInput||0)>500)p.input={};move(p,p.input,dt);if(p.input.fire&&now-p.lastShot>=180)shoot(p,now);}if(!rooms.has(p.room))rooms.set(p.room,[]);rooms.get(p.room).push({id:p.id,name:p.name,x:p.x,z:p.z,yaw:p.yaw,pitch:p.pitch,hp:p.hp,kills:p.kills,deaths:p.deaths,respawn:Math.max(0,p.respawnAt-now),shield:p.protectedUntil>now});}for(const[room,list]of rooms)broadcast(room,{type:'state',players:list});},1000/30);
server.listen(port,'0.0.0.0',()=>console.log(`NEON CROSSFIRE listening on 0.0.0.0:${port}`));
